import "./globals.css";
import { Nunito } from "next/font/google";
import GlobalProvider from "@/components/custom/globalProvider";
import { ToastContainer } from "react-toastify";

const nunitoFont = Nunito({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunitoFont.className} antialiased`}>
        <GlobalProvider>
          <ToastContainer />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
