import {
  ADMIN_DASHBOARD,
  ADMIN_CATEGORY,
  ADMIN_CATEGORY_ADD,
  ADMIN_PRODUCT,
  ADMIN_PRODUCT_ADD,
  ADMIN_VARIANT,
  ADMIN_VARIANT_ADD,
  ADMIN_COUPON,
  ADMIN_COUPON_ADD,
  ADMIN_ORDERS,
  ADMIN_CUSTOMERS,
  ADMIN_REVIEW,
  ADMIN_MEDIA,
} from "@/routes/AdminRoute";

const searchData = [
  {
    label: "Dashboard",
    description: "View overall site statistics and analytics",
    keywords: ["dashboard", "view", "overview", "statistics", "analytics"],
    url: ADMIN_DASHBOARD,
  },
  {
    label: "Category",
    description: "Manage all product categories",
    keywords: [
      "category",
      "categories",
      "manage",
      "product category",
      "product categories",
    ],
    url: ADMIN_CATEGORY,
  },
  {
    label: "Add Category",
    description: "Add a new product category",
    keywords: [
      "add category",
      "add categories",
      "add",
      "new product category",
      "new product categories",
      "new category",
      "new categories",
    ],
    url: ADMIN_CATEGORY_ADD,
  },
  {
    label: "Product",
    description: "Manage all products in the catalog",
    keywords: [
      "product",
      "products",
      "manage",
      "product catalog",
      "product catalogs",
      "catalog",
      "catalogs",
    ],
    url: ADMIN_PRODUCT,
  },
  {
    label: "Add Product",
    description: "Add a new product to the catalog",
    keywords: [
      "add product",
      "add products",
      "add",
      "new product",
      "new products",
      "new product catalog",
      "new product catalogs",
      "new catalog",
      "new catalogs",
    ],
    url: ADMIN_PRODUCT_ADD,
  },
  {
    label: "Variant",
    description: "Manage product variants",
    keywords: [
      "variant",
      "variants",
      "manage",
      "product variant",
      "product variants",
    ],
    url: ADMIN_VARIANT,
  },
  {
    label: "Add Variant",
    description: "Add a new product variant",
    keywords: [
      "add variant",
      "add variants",
      "add",
      "new product variant",
      "new product variants",
      "new variant",
      "new variants",
    ],
    url: ADMIN_VARIANT_ADD,
  },
  {
    label: "Coupon",
    description: "Manage discount coupons",
    keywords: ["coupon", "coupons", "manage", "discount", "discounts"],
    url: ADMIN_COUPON,
  },
  {
    label: "Add Coupon",
    description: "Create a new discount coupon",
    keywords: [
      "add coupon",
      "add coupons",
      "add",
      "new discount",
      "new discounts",
      "new discount coupon",
      "new discount coupons",
      "new coupon",
      "new coupons",
    ],
    url: ADMIN_COUPON_ADD,
  },
  {
    label: "Orders",
    description: "View and manage customer orders",
    keywords: [
      "order",
      "orders",
      "manage",
      "customer order",
      "customer orders",
    ],
    url: ADMIN_ORDERS,
  },
  {
    label: "Customers",
    description: "Manage customer information and accounts",
    keywords: [
      "customer",
      "customers",
      "manage",
      "customer information",
      "information",
      "customer account",
      "customer accounts",
      "account",
      "accounts",
    ],
    url: ADMIN_CUSTOMERS,
  },
  {
    label: "Review",
    description: "Manage product reviews and ratings",
    keywords: [
      "review",
      "reviews",
      "manage",
      "product review",
      "product reviews",
      "product rating",
      "product ratings",
      "rating",
      "ratings",
    ],
    url: ADMIN_REVIEW,
  },

  {
    label: "Media",
    description: "Manage site media files like images",
    keywords: [
      "media",
      "manage",
      "site media",
      "media file",
      "media files",
      "file",
      "files",
      "image",
      "images",
    ],
    url: ADMIN_MEDIA,
  },
];

export default searchData;
